### ISSUE TITLE
Unable to have FlStudio 21 recognise the plugin

### ISSUE THREAD

**Issue by hbraasch** [DamRsn/NeuralNote#31] opened 2023-05-13 00:33 UTC
Really keen to try it out.

For some reason I am unable to have FlStudio 21 (latest release) recognise the plugin.

I exported the vst to a directory and setup FlStudio to be aware of it. 

Here is the vst in the directory...
![image](https://github.com/DamRsn/NeuralNote/assets/7484186/c5213409-818d-499e-b916-ce17c05cb75e)

Here is the proof the setup is correct and its unable to find it after a scan...
![image](https://github.com/DamRsn/NeuralNote/assets/7484186/fa1778fc-f296-4e84-9c65-5fd8501ce999)

I've done vst adding many times before in FlStudio, so the process is well understood by me.

Any suggestions please?

**Comment by TeamBirdy** [comment] 2023-05-13 01:30
Same issue on protools with windows

**Comment by DamRsn** [comment] 2023-05-21 11:17
Hi,

I don't have any way to reproduce this issue right now as I don't have access to a Windows machine at the moment. 

My guess is that it is because the plugin is not signed on Windows and FlStudio somehow blocks unsigned plugins from being registered. 

You could try to move the `NeuralNote.vst3` file in a more standard directory for VSTs, see if it makes a difference.

**Comment by abbesatty** [comment] 2023-05-22 20:40
I solved the issue with FL Studio ( _mine is on Windows 10_) not recognizing the plugin with these 2 simple  steps:
1- Put the vst3 file inside "C:\Program Files\Common Files\VST3",
2- Make sure "Verify Plugins" is checked in Plugins Manager.
![neuralnote-flstudio-github](https://github.com/DamRsn/NeuralNote/assets/134330988/607df708-0ec3-413d-8e2c-997597d6043a)

**Comment by DamRsn** [comment] 2023-08-07 09:20
Closing as it seems to be solved.

**Closed by DamRsn** 2023-08-07 09:20 UTC
